// console.log(`Current URL = ${window.location.href}`)

/*
    - TODO:
1. Update on url-change, not using alarm API

2. onInstalled query everything
*/


// Function for changing favicon
function changeFavicon(src) {
    var link = document.createElement('link'),
        oldLink = document.getElementById('dynamic-favicon');
    link.id = 'dynamic-favicon';
    link.rel = 'shortcut icon';
    link.href = src;
    if (oldLink) {
     document.head.removeChild(oldLink);
    }
    document.head.appendChild(link);
}

// Structure for iconmappers: {"Parameter to search for in subtitle": "favicon url"}

// Maps to icon from subtitletext
iconMapperSubtitleText = {
    // Web stuff
    "Function App": "https://azure-favicons-bucket.s3.amazonaws.com/Function+App.ico",
    "App Service": "https://azure-favicons-bucket.s3.amazonaws.com/App+Service.ico",
    "Static Web App": "https://azure-favicons-bucket.s3.amazonaws.com/Static+Web+Apps.ico",
    // Logic app
    "Logic App": "https://azure-favicons-bucket.s3.amazonaws.com/Logic+app+designer.ico",
    "Logic app": "https://azure-favicons-bucket.s3.amazonaws.com/Logic+app+designer.ico",
    // Key vault
    "Key vault": "https://azure-favicons-bucket.s3.amazonaws.com/Key+vault.ico",
    // Resource groups - holds multiple resources
    "Resource group": "https://azure-favicons-bucket.s3.amazonaws.com/Resource+groups.ico",
    // Subscriptions
    "Subscription": "https://azure-favicons-bucket.s3.amazonaws.com/Subscriptions.ico",
    // Storage account
    "Storage account": "https://azure-favicons-bucket.s3.amazonaws.com/Storage+account.ico",
    // Virtual machine
    "Virtual machine": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+machine.ico",
    "Scale set instance": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+machine.ico",
    // Virtual machine scale sets
    "Virtual machine scale set": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+machine+scale+sets.ico",
    // Cost management and billing
    "Billing account": "https://azure-favicons-bucket.s3.amazonaws.com/Cost+Management.ico",
    "Cost Management + Billing | Billing account": "https://azure-favicons-bucket.s3.amazonaws.com/cost-management.ico",
    // Deplyoment page
    "Deployment": "https://azure-favicons-bucket.s3.amazonaws.com/Deployment.ico",
    // Management group - holds multiple subscriptions
    "Management group": "https://azure-favicons-bucket.s3.amazonaws.com/Management+groups.ico",
    // "Shared dashboard": "https://azure-favicons-bucket.s3.amazonaws.com/Shared+dashboards.ico",
    // "Private dashboard": "https://azure-favicons-bucket.s3.amazonaws.com/Shared+dashboards.ico",
    "Container instances": "https://azure-favicons-bucket.s3.amazonaws.com/Container+instances.ico",
    "Batch account": "https://azure-favicons-bucket.s3.amazonaws.com/Batch+accounts.ico",
    "Service Fabric cluster": "https://azure-favicons-bucket.s3.amazonaws.com/Service+Fabric+clusters.ico",     // Untested
    "Cloud service (classic)": "https://azure-favicons-bucket.s3.amazonaws.com/Cloud+services+(classic).ico",
    "Kubernetes service": "https://azure-favicons-bucket.s3.amazonaws.com/Kubernetes+services.ico",
    "Availability set": "https://azure-favicons-bucket.s3.amazonaws.com/Availability+sets.ico",
    "Disk": "https://azure-favicons-bucket.s3.amazonaws.com/Disks+(classic).ico",
    "Proximity placement group": "https://azure-favicons-bucket.s3.amazonaws.com/Proximity+placement+groups.ico",
    "Host group": "https://azure-favicons-bucket.s3.amazonaws.com/Host+groups.ico",
    "Host": "https://azure-favicons-bucket.s3.amazonaws.com/Hosts.ico", // Untested
    "Azure Spring Apps": "https://azure-favicons-bucket.s3.amazonaws.com/Azure+Spring+Apps.ico",
    "Application group": "https://azure-favicons-bucket.s3.amazonaws.com/Application+groups.ico", // Untested
    "Maintenance Configuration": "https://azure-favicons-bucket.s3.amazonaws.com/Maintenance+Configurations.ico",
    "Workspace": "https://azure-favicons-bucket.s3.amazonaws.com/Workspaces.ico",
    "Container App": "https://azure-favicons-bucket.s3.amazonaws.com/Container+Apps.ico",
    "Virtual network": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+networks.ico",
    "Front Door and CDN profiles": "https://azure-favicons-bucket.s3.amazonaws.com/Front+Door+and+CDN+profiles.ico",
    "Network interface": "https://azure-favicons-bucket.s3.amazonaws.com/Network+interfaces.ico",
    "Route table": "https://azure-favicons-bucket.s3.amazonaws.com/Route+tables.ico",
    "Service endpoint policy": "https://azure-favicons-bucket.s3.amazonaws.com/Service+endpoint+policies.ico",
    "Private endpoint": "https://azure-favicons-bucket.s3.amazonaws.com/Private+Link.ico", // Untested
    "Private link service": "https://azure-favicons-bucket.s3.amazonaws.com/Private+Link.ico", // Untested
    "DNS zone": "https://azure-favicons-bucket.s3.amazonaws.com/Private+DNS+zones.ico",
    "NAT gateway": "https://azure-favicons-bucket.s3.amazonaws.com/NAT+gateways.ico",
    "Firewall Policy": "https://azure-favicons-bucket.s3.amazonaws.com/Firewall+Policies.ico",
};

// Most of the parameters are the same as the "iconMapperSubtitleText", but with an added 's'
// Maps to icon from title text
iconMapperTitleText = {
    "Resource groups": "https://azure-favicons-bucket.s3.amazonaws.com/Resource+groups.ico",
    "Virtual machines": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+machine.ico",
    "Recent": "https://azure-favicons-bucket.s3.amazonaws.com/Recent.ico",
    "Management groups": "https://azure-favicons-bucket.s3.amazonaws.com/Management+groups.ico",
    "Subscriptions": "https://azure-favicons-bucket.s3.amazonaws.com/Subscriptions.ico",
    "Marketplace": "https://azure-favicons-bucket.s3.amazonaws.com/Marketplace.ico",
    "Help + support": "https://azure-favicons-bucket.s3.amazonaws.com/Help+%2B+support.ico",
    "Service Health | Service issues": "https://azure-favicons-bucket.s3.amazonaws.com/Service+Health.ico",
    // templates: template-ico
    "Tags": "https://azure-favicons-bucket.s3.amazonaws.com/Tags.ico",
    "What's new": "https://azure-favicons-bucket.s3.amazonaws.com/What's+new.ico",
    "Quickstart Center": "https://azure-favicons-bucket.s3.amazonaws.com/Quickstart+Center.ico",
    "Shared dashboards": "https://azure-favicons-bucket.s3.amazonaws.com/Shared+dashboards.ico",
    "Free services": "https://azure-favicons-bucket.s3.amazonaws.com/Free+services.ico",
    // "Reservations": ""
    "Resource Explorer": "https://azure-favicons-bucket.s3.amazonaws.com/Resource+Explorer.ico",
    "Logic apps": "https://azure-favicons-bucket.s3.amazonaws.com/Logic+app+designer.ico",
    "Create Logic App": "https://azure-favicons-bucket.s3.amazonaws.com/Logic+app+designer.ico",
    "Logic Apps Designer": "https://azure-favicons-bucket.s3.amazonaws.com/Logic+app+designer.ico",
    "Virtual machine scale sets": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+machine+scale+sets.ico",
    "Create a virtual machine scale set": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+machine+scale+sets.ico",
    "Function App": "https://azure-favicons-bucket.s3.amazonaws.com/Function+App.ico",
    "Create Function App": "https://azure-favicons-bucket.s3.amazonaws.com/Function+App.ico",
    "App Services": "https://azure-favicons-bucket.s3.amazonaws.com/App+Service.ico",
    "Create Web App": "https://azure-favicons-bucket.s3.amazonaws.com/App+Service.ico",
    "Container instances": "https://azure-favicons-bucket.s3.amazonaws.com/Container+instances.ico",
    "Create container instance": "https://azure-favicons-bucket.s3.amazonaws.com/Container+instances.ico",
    "Batch accounts": "https://azure-favicons-bucket.s3.amazonaws.com/Batch+accounts.ico",
    "New Batch account": "https://azure-favicons-bucket.s3.amazonaws.com/Batch+accounts.ico",
    "Service Fabric clusters": "https://azure-favicons-bucket.s3.amazonaws.com/Service+Fabric+clusters.ico",
    "All resources": "https://azure-favicons-bucket.s3.amazonaws.com/All+resources.ico",
    "Cloud services (classic)": "https://azure-favicons-bucket.s3.amazonaws.com/Cloud+services+(classic).ico",
    "Create a cloud service": "https://azure-favicons-bucket.s3.amazonaws.com/Cloud+services+(classic).ico",
    "Kubernetes services": "https://azure-favicons-bucket.s3.amazonaws.com/Kubernetes+services.ico",
    "Kubernetes Service": "https://azure-favicons-bucket.s3.amazonaws.com/Kubernetes+services.ico",
    "Create Kubernetes cluster": "https://azure-favicons-bucket.s3.amazonaws.com/Kubernetes+services.ico",
    "Availability sets": "https://azure-favicons-bucket.s3.amazonaws.com/Availability+sets.ico",
    "Create availability set": "https://azure-favicons-bucket.s3.amazonaws.com/Availability+sets.ico",
    "Disks (classic)": "https://azure-favicons-bucket.s3.amazonaws.com/Disks+(classic).ico",
    "Create disk": "https://azure-favicons-bucket.s3.amazonaws.com/Disks+(classic).ico",
    "OS images (classic)": "https://azure-favicons-bucket.s3.amazonaws.com/OS+images+(classic).ico",
    "VM images (classic)": "https://azure-favicons-bucket.s3.amazonaws.com/OS+images+(classic).ico",
    "Create VM image": "https://azure-favicons-bucket.s3.amazonaws.com/OS+images+(classic).ico",
    "Citrix Virtual Apps Essentials": "https://azure-favicons-bucket.s3.amazonaws.com/Citrix+Virtual+Desktops+Essentials.ico",
    "Citrix Virtual Desktops Essentials": "https://azure-favicons-bucket.s3.amazonaws.com/Citrix+Virtual+Desktops+Essentials.ico",
    "SAP HANA on Azure": "https://azure-favicons-bucket.s3.amazonaws.com/SAP+HANA+on+Azure.ico",
    "Proximity placement groups": "https://azure-favicons-bucket.s3.amazonaws.com/Proximity+placement+groups.ico",
    "Create Proximity Placement Group": "https://azure-favicons-bucket.s3.amazonaws.com/Proximity+placement+groups.ico",
    "Host groups": "https://azure-favicons-bucket.s3.amazonaws.com/Host+groups.ico",
    "Create host group": "https://azure-favicons-bucket.s3.amazonaws.com/Host+groups.ico",
    "Hosts": "https://azure-favicons-bucket.s3.amazonaws.com/Hosts.ico",
    "Create dedicated host": "https://azure-favicons-bucket.s3.amazonaws.com/Hosts.ico",
    "Azure Spring Apps": "https://azure-favicons-bucket.s3.amazonaws.com/Azure+Spring+Apps.ico",
    "Application groups": "https://azure-favicons-bucket.s3.amazonaws.com/Application+groups.ico",
    "Create an application group": "https://azure-favicons-bucket.s3.amazonaws.com/Application+groups.ico",
    "Maintenance Configurations": "https://azure-favicons-bucket.s3.amazonaws.com/Maintenance+Configurations.ico",
    "Create a maintenance configurations": "https://azure-favicons-bucket.s3.amazonaws.com/Maintenance+Configurations.ico",
    "Workspaces": "https://azure-favicons-bucket.s3.amazonaws.com/Workspaces.ico",
    "Create a workspace": "https://azure-favicons-bucket.s3.amazonaws.com/Workspaces.ico",
    "Container Apps": "https://azure-favicons-bucket.s3.amazonaws.com/Container+Apps.ico",
    "Create Container App": "https://azure-favicons-bucket.s3.amazonaws.com/Container+Apps.ico",
    "Virtual networks": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+networks.ico",
    "Create virtual network": "https://azure-favicons-bucket.s3.amazonaws.com/Virtual+networks.ico",
    "Front Door and CDN profiles": "https://azure-favicons-bucket.s3.amazonaws.com/Front+Door+and+CDN+profiles.ico",
    "Create a Front Door profile": "https://azure-favicons-bucket.s3.amazonaws.com/Front+Door+and+CDN+profiles.ico",
    "Network interfaces": "https://azure-favicons-bucket.s3.amazonaws.com/Network+interfaces.ico",
    "Create network interface": "https://azure-favicons-bucket.s3.amazonaws.com/Network+interfaces.ico",
    "Route tables": "https://azure-favicons-bucket.s3.amazonaws.com/Route+tables.ico",
    "Service endpoint policies": "https://azure-favicons-bucket.s3.amazonaws.com/Service+endpoint+policies.ico",
    "Create a service endpoint policy": "https://azure-favicons-bucket.s3.amazonaws.com/Service+endpoint+policies.ico",
    "Private Link Center": "https://azure-favicons-bucket.s3.amazonaws.com/Private+Link.ico",
    "Create a private endpoint": "https://azure-favicons-bucket.s3.amazonaws.com/Private+Link.ico",
    "Create private link service": "https://azure-favicons-bucket.s3.amazonaws.com/Private+Link.ico",
    "DNS zones": "https://azure-favicons-bucket.s3.amazonaws.com/Private+DNS+zones.ico",
    "Create DNS zones": "https://azure-favicons-bucket.s3.amazonaws.com/Private+DNS+zones.ico",
    "NAT gateways": "https://azure-favicons-bucket.s3.amazonaws.com/NAT+gateways.ico",
    "Create network address translation (NAT) gateway": "https://azure-favicons-bucket.s3.amazonaws.com/NAT+gateways.ico",
    "Firewall Policies": "https://azure-favicons-bucket.s3.amazonaws.com/Firewall+Policies.ico",
    "Create an Azure Firewall Policy": "https://azure-favicons-bucket.s3.amazonaws.com/Firewall+Policies.ico",
};

// The default fallback method
iconMapperAllText = {
    "fxsymbol0-1c1": "FxSymbol0-1c1.ico",
    "devices": "Devices.ico",
    "fxsymbol0-031": "FxSymbol0-031.ico",
    "azuremachinelearning": "Azure Machine Learning.ico",
    "azurecomputegalleries": "Azure compute galleries.ico",
    "restorepointcollections": "Restore Point Collections.ico",
    "deploymentscripts": "Deployment Scripts.ico",
    "iotcentralapplications": "IoT Central Applications.ico",
    "logicappscustomconnector": "Logic Apps Custom Connector.ico",
    "notificationhubs": "Notification Hubs.ico",
    "streamanalyticsjobs": "Stream Analytics jobs.ico",
    "feedback": "Feedback.ico",
    "notifications": "Notifications.ico",
    "medtechservice": "MedTech service.ico",
    "powerplatform": "Power Platform.ico",
    "timeseriesinsightsenvironments": "Time Series Insights environments.ico",
    "universalprint": "Universal Print.ico",
    "customerlockboxformicrosoftazure": "Customer Lockbox for Microsoft Azure.ico",
    "chaosexperiments": "Chaos Experiments.ico",
    "cross-tenantsynchronization": "Cross-tenant Synchronization.ico",
    "hostgroups": "Host groups.ico",
    "autoscale": "Autoscale.ico",
    "templatespecs": "Template specs.ico",
    "applicationgroups": "Application groups.ico",
    "fxsymbol0-1ab": "FxSymbol0-1ab.ico",
    "containerappsenvironments": "Container Apps Environments.ico",
    "proximityplacementgroups": "Proximity placement groups.ico",
    "datalakestoragegen1": "Data Lake Storage Gen1.ico",
    "datashareinvitations": "Data Share Invitations.ico",
    "managedidentities": "Managed Identities.ico",
    "loadbalancers": "Load balancers.ico",
    "appserviceplans": "App Service plans.ico",
    "mobilenetworks": "Mobile Networks.ico",
    "sqldatabases": "SQL databases.ico",
    "appproxy": "App proxy.ico",
    "staticwebapps": "Static Web Apps.ico",
    "solutions": "Solutions.ico",
    "activitylog": "Activity log.ico",
    "eventhubsclusters": "Event Hubs Clusters.ico",
    "azurecacheforredis": "Azure Cache for Redis.ico",
    "azureiothubdeviceprovisioningservices": "Azure IoT Hub Device Provisioning Services.ico",
    "azureactivedirectory": "Azure Active Directory.ico",
    "microsoftsentinel": "Microsoft Sentinel.ico",
    "fxsymbol0-026": "FxSymbol0-026.ico",
    "deviceupdateforiothubs": "Device Update for IoT Hubs.ico",
    "signalr": "SignalR.ico",
    "servicehealth": "Service Health.ico",
    "iothub": "IoT Hub.ico",
    "multifactorauthentication": "Multifactor authentication.ico",
    "customipprefixes": "Custom IP Prefixes.ico",
    "containerinstances": "Container instances.ico",
    "ipgroups": "IP Groups.ico",
    "vmimageversions": "VM image versions.ico",
    "azureadrolesandadministrators": "Azure AD roles and administrators.ico",
    "applicationserverinstancesforsapsolutions": "Application server instances for SAP solutions.ico",
    "chaosstudio": "Chaos Studio.ico",
    "fxsymbol0-1c4": "FxSymbol0-1c4.ico",
    "azureworkbooks": "Azure Workbooks.ico",
    "reservations": "Reservations.ico",
    "quickstartcenter": "Quickstart Center.ico",
    "fxsymbol0-00f": "FxSymbol0-00f.ico",
    "loadbalancing-helpmechoose": "Load balancing - help me choose.ico",
    "what'snew": "What's new.ico",
    "datafactories": "Data factories.ico",
    "routetables": "Route tables.ico",
    "fxsymbol0-1be": "FxSymbol0-1be.ico",
    "azuredatabricks": "Azure Databricks.ico",
    "timeseriesinsightsreferencedatasets": "Time Series Insights reference data sets.ico",
    "directories+subscriptions": "Directories + subscriptions.ico",
    "azuredatabox": "Azure Data Box.ico",
    "dnsprivateresolvers": "DNS Private Resolvers.ico",
    "videoanalyzers": "Video Analyzers.ico",
    "managedapplications": "Managed applications.ico",
    "microsoftdefenderforcloud": "Microsoft Defender for Cloud.ico",
    "advisor": "Advisor.ico",
    "fxsymbol0-1af": "FxSymbol0-1af.ico",
    "fxsymbol0-1b3": "FxSymbol0-1b3.ico",
    "fxsymbol0-1bf": "FxSymbol0-1bf.ico",
    "resourceguards": "Resource Guards.ico",
    "devopsstarter": "DevOps Starter.ico",
    "azureadsecurity": "Azure AD Security.ico",
    "fxsymbol0-1ca": "FxSymbol0-1ca.ico",
    "fxsymbol0-01e": "FxSymbol0-01e.ico",
    "routeservers": "Route Servers.ico",
    "microsoftdefenderforiot": "Microsoft Defender for IoT.ico",
    "fxsymbol0-1b9": "FxSymbol0-1b9.ico",
    "azureapiforfhir": "Azure API for FHIR.ico",
    "genomicsaccounts": "Genomics accounts.ico",
    "disks(classic)": "Disks (classic).ico",
    "azureopenai": "Azure OpenAI.ico",
    "integrationaccounts": "Integration accounts.ico",
    "azurecosmosdb": "Azure Cosmos DB.ico",
    "webpubsubservice": "Web PubSub Service.ico",
    "allresources": "All resources.ico",
    "fxsymbol0-1c3": "FxSymbol0-1c3.ico",
    "azurenetworkfunctionmanager–vendors": "Azure Network Function Manager – Vendors.ico",
    "azurearcprivatelinkscopes": "Azure Arc Private Link Scopes.ico",
    "userprivacy": "User privacy.ico",
    "fxsymbol0-1b8": "FxSymbol0-1b8.ico",
    "policy": "Policy.ico",
    "saphanaonazure": "SAP HANA on Azure.ico",
    "customlocations": "Custom locations.ico",
    "externalidentities": "External Identities.ico",
    "language": "Language.ico",
    "contentmoderators": "Content moderators.ico",
    "virtualvisitsbuilder": "Virtual Visits Builder.ico",
    "firewallmanager": "Firewall Manager.ico",
    "verifiedid": "Verified ID.ico",
    "vmwarevcenters": "VMware vCenters.ico",
    "virtualmachines": "Virtual machines.ico",
    "reservedipaddresses(classic)": "Reserved IP addresses (classic).ico",
    "labs": "Labs.ico",
    "azureperceptstudio": "Azure Percept Studio.ico",
    "fxsymbol0-1b7": "FxSymbol0-1b7.ico",
    "fxsymbol0-024": "FxSymbol0-024.ico",
    "servicefabricclusters": "Service Fabric clusters.ico",
    "bastions": "Bastions.ico",
    "fluidrelay": "Fluid Relay.ico",
    "fxsymbol0-029": "FxSymbol0-029.ico",
    "eventgridsystemtopics": "Event Grid System Topics.ico",
    "azureredhatopenshift": "Azure Red Hat OpenShift.ico",
    "identitygovernance": "Identity Governance.ico",
    "intune": "Intune.ico",
    "dynatrace": "Dynatrace.ico",
    "fxsymbol0-022": "FxSymbol0-022.ico",
    "privatelinkservices": "Private link services.ico",
    "fxsymbol0-1ac": "FxSymbol0-1ac.ico",
    "azuresynapseanalytics": "Azure Synapse Analytics.ico",
    "firewallpolicies": "Firewall Policies.ico",
    "fxsymbol0-00e": "FxSymbol0-00e.ico",
    "quotas": "Quotas.ico",
    "guestassignments": "Guest Assignments.ico",
    "elasticsearch(elasticcloud)": "Elasticsearch (Elastic Cloud).ico",
    "azurestacke": "Azure Stack E.ico",
    "vmapplicationversions": "VM application versions.ico",
    "imagetemplates": "Image templates.ico",
    "virtualnetworks": "Virtual networks.ico",
    "fxsymbol0-1bc": "FxSymbol0-1bc.ico",
    "privateendpoints": "Private endpoints.ico",
    "fxsymbol0-1b5": "FxSymbol0-1b5.ico",
    "virtualmachines(classic)": "Virtual machines (classic).ico",
    "cloudshell": "Cloud Shell.ico",
    "storsimpledatamanagers": "StorSimple Data Managers.ico",
    "fxsymbol0-014": "FxSymbol0-014.ico",
    "virtualnetworks(classic)": "Virtual networks (classic).ico",
    "bonsai": "Bonsai.ico",
    "fxsymbol0-1a7": "FxSymbol0-1a7.ico",
    "fxsymbol0-1b0": "FxSymbol0-1b0.ico",
    "azureedgehardwarecenter": "Azure Edge Hardware Center.ico",
    "on-premisesdatagateways": "On-premises data gateways.ico",
    "cognitivesearch": "Cognitive Search.ico",
    "images": "Images.ico",
    "diskpools": "Disk Pools.ico",
    "azuredataboxgateway": "Azure Data Box Gateway.ico",
    "hosts": "Hosts.ico",
    "datalakeanalytics": "Data Lake Analytics.ico",
    "hpccaches": "HPC caches.ico",
    "personalizers": "Personalizers.ico",
    "changeanalysis": "Change Analysis.ico",
    "machinelearningstudio(classic)webserviceplans": "Machine Learning Studio (classic) web service plans.ico",
    "azureadprivilegedidentitymanagement": "Azure AD Privileged Identity Management.ico",
    "fxsymbol0-011": "FxSymbol0-011.ico",
    "azuredatabasemigrationprojects": "Azure Database Migration Projects.ico",
    "apimanagementservices": "API Management services.ico",
    "languageunderstanding": "Language understanding.ico",
    "networkmanagers": "Network Managers.ico",
    "azurevirtualdesktop": "Azure Virtual Desktop.ico",
    "sqlvirtualmachines": "SQL virtual machines.ico",
    "faceapis": "Face APIs.ico",
    "appserviceenvironments": "App Service Environments.ico",
    "eventhubs": "Event Hubs.ico",
    "azuredatabaseforpostgresqlservers": "Azure Database for PostgreSQL servers.ico",
    "fhirservice": "FHIR service.ico",
    "applicationgateways": "Application gateways.ico",
    "elasticjobagents": "Elastic Job agents.ico",
    "manageddatabases": "Managed databases.ico",
    "eventgriddomains": "Event Grid Domains.ico",
    "fxsymbol0-027": "FxSymbol0-027.ico",
    "esrpscan": "ESRP Scan.ico",
    "directory+subscription": "Directory + Subscription.ico",
    "sqlelasticpools": "SQL elastic pools.ico",
    "azuredataexplorerclusters": "Azure Data Explorer Clusters.ico",
    "fxsymbol0-01b": "FxSymbol0-01b.ico",
    "azurecenterforsapsolutions": "Azure Center for SAP solutions.ico",
    "emailcommunicationservices": "Email Communication Services.ico",
    "routefilters": "Route filters.ico",
    "expressroutetrafficcollectors": "ExpressRoute traffic collectors.ico",
    "azurearcdatacontrollers": "Azure Arc data controllers.ico",
    "createcustomazureadroles": "Create custom Azure AD roles.ico",
    "windows10iotcoreservices": "Windows 10 IoT Core Services.ico",
    "scanxmanagement": "ScanX Management.ico",
    "cognitiveservices": "Cognitive Services.ico",
    "baremetalinstances": "BareMetal Instances.ico",
    "diskencryptionsets": "Disk Encryption Sets.ico",
    "sqlserverregistries": "SQL Server registries.ico",
    "costexports": "Cost exports.ico",
    "microsoftdefendereasm": "Microsoft Defender EASM.ico",
    "subscriptions": "Subscriptions.ico",
    "appconfiguration": "App Configuration.ico",
    "costmanagement": "Cost Management.ico",
    "fxsymbol0-010": "FxSymbol0-010.ico",
    "users": "Users.ico",
    "vmimagedefinitions": "VM image definitions.ico",
    "nginxdeployment": "NGINX Deployment.ico",
    "alerts": "Alerts.ico",
    "datashares": "Data Shares.ico",
    "azuredatabaseformysqlservers": "Azure Database for MySQL servers.ico",
    "monitor": "Monitor.ico",
    "streamanalyticsclusters": "Stream Analytics clusters.ico",
    "privatednszones": "Private DNS zones.ico",
    "budgets": "Budgets.ico",
    "powerbiembedded": "Power BI Embedded.ico",
    "datacatalog": "Data Catalog.ico",
    "mycustomers": "My customers.ico",
    "virtualmachinescalesets": "Virtual machine scale sets.ico",
    "natgateways": "NAT gateways.ico",
    "azureresourcemover": "Azure Resource Mover.ico",
    "fxsymbol0-1c7": "FxSymbol0-1c7.ico",
    "metrics": "Metrics.ico",
    "expressroutecircuits": "ExpressRoute circuits.ico",
    "fxsymbol0-005": "FxSymbol0-005.ico",
    "saas(classic)": "SaaS (classic).ico",
    "speechservices": "Speech services.ico",
    "azuremonitorsforsapsolutions": "Azure Monitors for SAP solutions.ico",
    "azureadb2c": "Azure AD B2C.ico",
    "azuredatabaseformariadbservers": "Azure Database for MariaDB servers.ico",
    "managedapplicationscenter": "Managed applications center.ico",
    "servers-azurearc": "Servers - Azure Arc.ico",
    "fxsymbol0-1cc": "FxSymbol0-1cc.ico",
    "formrecognizers": "Form recognizers.ico",
    "fxsymbol0-1bb": "FxSymbol0-1bb.ico",
    "fxsymbol0-1c6": "FxSymbol0-1c6.ico",
    "azurelighthouse": "Azure Lighthouse.ico",
    "fxsymbol0-1bd": "FxSymbol0-1bd.ico",
    "blueprints": "Blueprints.ico",
    "servicecatalogmanagedapplicationdefinitions": "Service catalog managed application definitions.ico",
    "fxsymbol0-1c2": "FxSymbol0-1c2.ico",
    "vmapplicationdefinitions": "VM application definitions.ico",
    "fxsymbol0-012": "FxSymbol0-012.ico",
    "azuredeploymentenvironments": "Azure Deployment Environments.ico",
    "recent": "Recent.ico",
    "metricsadvisors": "Metrics advisors.ico",
    "resourcegraphexplorer": "Resource Graph Explorer.ico",
    "automationaccounts": "Automation Accounts.ico",
    "back": "Back.ico",
    "scalingplans": "Scaling plans.ico",
    "azureinformationprotection": "Azure Information Protection.ico",
    "testbaseformicrosoft365": "Test Base for Microsoft 365.ico",
    "eventgridpartnernamespaces": "Event Grid Partner Namespaces.ico",
    "fxsymbol0-1ad": "FxSymbol0-1ad.ico",
    "resourcemanagementprivatelinks": "Resource management private links.ico",
    "azureaddomainservices": "Azure AD Domain Services.ico",
    "containerapps": "Container Apps.ico",
    "serviceshubconnectors": "Services Hub Connectors.ico",
    "administrativeunits": "Administrative units.ico",
    "quantumworkspaces": "Quantum Workspaces.ico",
    "privatelink": "Private Link.ico",
    "fxsymbol0-1b4": "FxSymbol0-1b4.ico",
    "shareddashboards": "Shared dashboards.ico",
    "showportalmenu": "Show portal menu.ico",
    "projects": "Projects.ico",
    "timeseriesinsightseventsources": "Time Series Insights event sources.ico",
    "spatialanchorsaccounts": "Spatial Anchors Accounts.ico",
    "support&troubleshooting": "Support & Troubleshooting.ico",
    "logicapps": "Logic apps.ico",
    "azuremanagedgrafana": "Azure Managed Grafana.ico",
    "resourceexplorer": "Resource Explorer.ico",
    "threatmanagement": "Threat management.ico",
    "azureadidentitysecurescore": "Azure AD Identity Secure Score.ico",
    "rollouts": "Rollouts.ico",
    "loganalyticsquerypacks": "Log Analytics query packs.ico",
    "communicationservices": "Communication Services.ico",
    "storageaccounts(classic)": "Storage accounts (classic).ico",
    "sqlmanagedinstances": "SQL managed instances.ico",
    "webapplicationfirewallpolicies(waf)": "Web Application Firewall policies (WAF).ico",
    "fxsymbol0-1b2": "FxSymbol0-1b2.ico",
    "azuresynapseanalytics(privatelinkhubs)": "Azure Synapse Analytics (private link hubs).ico",
    "applicationinsights": "Application Insights.ico",
    "azurenetworkfunctionmanager–networkfunctions": "Azure Network Function Manager – Network Functions.ico",
    "anomalydetectors": "Anomaly detectors.ico",
    "peeringservices": "Peering Services.ico",
    "azureadconnecthealth": "Azure AD Connect Health.ico",
    "applicationsecuritygroups": "Application security groups.ico",
    "fxsymbol0-020": "FxSymbol0-020.ico",
    "sqlservers": "SQL servers.ico",
    "servicefabricmanagedclusters": "Service Fabric managed clusters.ico",
    "azurelabservices": "Azure Lab Services.ico",
    "azurenetappfiles": "Azure NetApp Files.ico",
    "eventgridpartnertopics": "Event Grid Partner Topics.ico",
    "fxsymbol0-1c8": "FxSymbol0-1c8.ico",
    "templates": "Templates.ico",
    "azurestackhci": "Azure Stack HCI.ico",
    "kubernetes-azurearc": "Kubernetes - Azure Arc.ico",
    "microsoftlearn": "Microsoft Learn.ico",
    "fxsymbol0-190": "FxSymbol0-190.ico",
    "storsimpledevicemanagers": "StorSimple Device Managers.ico",
    "extendedsecurityupdates": "Extended Security Updates.ico",
    "networkconnections": "Network connections.ico",
    "fxsymbol0-004": "FxSymbol0-004.ico",
    "publicipaddresses": "Public IP addresses.ico",
    "apiplayground": "API Playground.ico",
    "azurearc": "Azure Arc.ico",
    "loganalyticsworkspaces": "Log Analytics workspaces.ico",
    "videoindexer": "Video Indexer.ico",
    "azuredatabasemigrationservices": "Azure Database Migration Services.ico",
    "expressroutedirect": "ExpressRoute Direct.ico",
    "costanalysis(preview)": "Cost analysis (preview).ico",
    "virtualclusters": "Virtual clusters.ico",
    "accessconnectorforazuredatabricks": "Access Connector for Azure Databricks.ico",
    "freeservices": "Free services.ico",
    "fxsymbol0-1ba": "FxSymbol0-1ba.ico",
    "targetsmanagement": "Targets Management.ico",
    "snapshots": "Snapshots.ico",
    "workspaces": "Workspaces.ico",
    "previewfeatures": "Preview features.ico",
    "dedicatedsqlpools(formerlysqldw)": "Dedicated SQL pools (formerly SQL DW).ico",
    "intelligentrecommendationsaccounts": "Intelligent Recommendations Accounts.ico",
    "publicipprefixes": "Public IP Prefixes.ico",
    "machinelearningstudio(classic)webservices": "Machine Learning Studio (classic) web services.ico",
    "warning": "Warning.ico",
    "azureadriskyusers": "Azure AD Risky users.ico",
    "contactprofiles": "Contact Profiles.ico",
    "azuremanagedinstanceforapachecassandra": "Azure Managed Instance for Apache Cassandra.ico",
    "capacityreservationgroups": "Capacity Reservation Groups.ico",
    "appregistrations": "App registrations.ico",
    "elasticsans": "Elastic SANs.ico",
    "peerings": "Peerings.ico",
    "analysisservices": "Analysis Services.ico",
    "enterpriseapplications": "Enterprise applications.ico",
    "servicebus": "Service Bus.ico",
    "fxsymbol0-028": "FxSymbol0-028.ico",
    "fxsymbol0-1b1": "FxSymbol0-1b1.ico",
    "eventgridtopics": "Event Grid Topics.ico",
    "fxsymbol0-021": "FxSymbol0-021.ico",
    "firewalls": "Firewalls.ico",
    "keyvaults": "Key vaults.ico",
    "internetanalyzerprofiles": "Internet Analyzer profiles.ico",
    "im": "Im.ico",
    "storagebrowser": "Storage browser.ico",
    "customvision": "Custom vision.ico",
    "virtualinstancesforsapsolutions": "Virtual Instances for SAP solutions.ico",
    "storagesyncservices": "Storage Sync Services.ico",
    "fxsymbol0-1c5": "FxSymbol0-1c5.ico",
    "microsoftpurviewaccounts": "Microsoft Purview accounts.ico",
    "fxsymbol0-013": "FxSymbol0-013.ico",
    "serviceendpointpolicies": "Service endpoint policies.ico",
    "virtualwans": "Virtual WANs.ico",
    "networksecuritygroups": "Network security groups.ico",
    "resourcegroups": "Resource groups.ico",
    "updatemanagementcenter(preview)": "Update management center (Preview).ico",
    "azuredatabaseforpostgresqlhyperscale(citus)": "Azure Database for PostgreSQL Hyperscale (Citus).ico",
    "sshkeys": "SSH keys.ico",
    "dnsforwardingrulesets": "DNS Forwarding Rulesets.ico",
    "kubernetesfleetmanager": "Kubernetes fleet manager.ico",
    "qnamakers": "QnA makers.ico",
    "backupvaults": "Backup vaults.ico",
    "osimages(classic)": "OS images (classic).ico",
    "availabilitysets": "Availability sets.ico",
    "instancepools": "Instance pools.ico",
    "azurehealthbot": "Azure Health Bot.ico",
    "maintenanceconfigurations": "Maintenance Configurations.ico",
    "trafficmanagerprofiles": "Traffic Manager profiles.ico",
    "apiconnections": "API Connections.ico",
    "citrixvirtualdesktopsessentials": "Citrix Virtual Desktops Essentials.ico",
    "datadog": "Datadog.ico",
    "objectanchorsaccounts": "Object Anchors Accounts.ico",
    "fxsymbol0-1ae": "FxSymbol0-1ae.ico",
    "help+support": "Help + support.ico",
    "healthdecisionsupports": "Health decision supports.ico",
    "backupcenter": "Backup center.ico",
    "settings": "Settings.ico",
    "eventgridsubscriptions": "Event Grid Subscriptions.ico",
    "fxsymbol0-1aa": "FxSymbol0-1aa.ico",
    "virtualnetworkgateways": "Virtual network gateways.ico",
    "tags": "Tags.ico",
    "containerregistries": "Container registries.ico",
    "translators": "Translators.ico",
    "confidentialledgers": "Confidential Ledgers.ico",
    "azureadriskysign-ins": "Azure AD Risky sign-ins.ico",
    "spacecrafts": "Spacecrafts.ico",
    "usersettings": "User settings.ico",
    "eventgridpartnerdestinations": "Event Grid Partner Destinations.ico",
    "appservicedomains": "App Service Domains.ico",
    "azurespringapps": "Azure Spring Apps.ico",
    "hdinsightclusters": "HDInsight clusters.ico",
    "hostpools": "Host pools.ico",
    "networkinterfaces": "Network interfaces.ico",
    "resourcegraphqueries": "Resource Graph queries.ico",
    "computervision": "Computer vision.ico",
    "labplans": "Lab plans.ico",
    "cloudservices(classic)": "Cloud services (classic).ico",
    "fxsymbol0-1c9": "FxSymbol0-1c9.ico",
    "azurenetworkfunctionmanager–devices": "Azure Network Function Manager – Devices.ico",
    "immersivereaders": "Immersive readers.ico",
    "machinelearningstudio(classic)workspaces": "Machine Learning Studio (classic) workspaces.ico",
    "dicomservice": "DICOM service.ico",
    "networkwatcher": "Network Watcher.ico",
    "general": "General.ico",
    "diagnosticsettings": "Diagnostic settings.ico",
    "servicehealth": "Service health.ico",
    "botservices": "Bot Services.ico",
    "fxsymbol0-015": "FxSymbol0-015.ico",
    "labaccounts": "Lab accounts.ico",
    "functionapp": "Function App.ico",
    "meshvpns": "Mesh VPNs.ico",
    "remoterenderingaccounts": "Remote Rendering Accounts.ico",
    "fxsymbol0-1cb": "FxSymbol0-1cb.ico",
    "storageaccounts": "Storage accounts.ico",
    "sqlserver-azurearc": "SQL Server - Azure Arc.ico",
    "devtestlabs": "DevTest Labs.ico",
    "azureadidentityprotection": "Azure AD Identity Protection.ico",
    "centralservicesinstancesforsapsolutions": "Central services instances for SAP solutions.ico",
    "databaseinstancesforsapsolutions": "Database instances for SAP solutions.ico",
    "automanage": "Automanage.ico",
    "integrationserviceenvironments": "Integration Service Environments.ico",
    "confluentorganizations": "Confluent organizations.ico",
    "appservices": "App Services.ico",
    "mediaservices": "Media Services.ico",
    "fxsymbol0-016": "FxSymbol0-016.ico",
    "azureorbital": "Azure Orbital.ico",
    "livedatamigrators": "LiveData Migrators.ico",
    "recoveryservicesvaults": "Recovery Services vaults.ico",
    "servicemenu": "Service menu.ico",
    "azureloadtesting": "Azure Load Testing.ico",
    "fxsymbol0-025": "FxSymbol0-025.ico",
    "sqlmanagedinstances-azurearc": "SQL managed instances - Azure Arc.ico",
    "resourcebridges": "Resource bridges.ico",
    "costalerts": "Cost alerts.ico",
    "relays": "Relays.ico",
    "serviceproviders": "Service providers.ico",
    "scvmmmanagementservers": "SCVMM management servers.ico",
    "azuredigitaltwins": "Azure Digital Twins.ico",
    "connections": "Connections.ico",
    "eventgridpartnerconfigurations": "Event Grid Partner Configurations.ico",
    "education": "Education.ico",
    "fxsymbol0-018": "FxSymbol0-018.ico",
    "appservicecertificates": "App Service Certificates.ico",
    "deployacustomtemplate": "Deploy a custom template.ico",
    "frontdoorandcdnprofiles": "Front Door and CDN profiles.ico",
    "azuremigrate": "Azure Migrate.ico",
    "azureadauthenticationmethods": "Azure AD Authentication methods.ico",
    "eventgridpartnerregistrations": "Event Grid Partner Registrations.ico",
    "azuremapsaccounts": "Azure Maps Accounts.ico",
    "kubernetesservices": "Kubernetes services.ico",
    "marketplace": "Marketplace.ico",
    "localnetworkgateways": "Local network gateways.ico",
    "storagemovers": "Storage movers.ico",
    "fxsymbol0-1b6": "FxSymbol0-1b6.ico",
    "securitybaselines": "Security Baselines.ico",
    "azureadconditionalaccess": "Azure AD Conditional Access.ico",
    "diskaccesses": "Disk Accesses.ico",
    "fxsymbol0-1c0": "FxSymbol0-1c0.ico",
    "cloudservices(extendedsupport)": "Cloud services (extended support).ico",
    "groups": "Groups.ico",
    "batchaccounts": "Batch accounts.ico",
    "azurevmwaresolution": "Azure VMware Solution.ico",
    "fxsymbol0-019": "FxSymbol0-019.ico",
    "costmanagement+billing": "Cost Management + Billing.ico",
    "ddosprotectionplans": "DDoS protection plans.ico",
    "managementgroups": "Management groups.ico",
};

// Get subtitletext of tab
var subtitleTexts = [].slice.call(document.getElementsByClassName("fxs-blade-title-subtitleText msportalfx-tooltip-overflow fxs-portal-subtext"));
subtitleTexts.reverse()

var titleTexts = [].slice.call(document.getElementsByClassName("fxs-blade-title-titleText msportalfx-tooltip-overflow"));
titleTexts.reverse()

function iconMapper() {
    // If homepage
    if (location.href.includes("portal.azure.com/#home") || location.href.includes("portal.azure.com/#allservices")) {
        // Change to default logo
        changeFavicon("https://azure-favicons-bucket.s3.amazonaws.com/home_400x400.ico");
    }

    // If site has subtitleText - change to match
    for (const subtitleText of subtitleTexts) {
        subText = subtitleText.textContent;
        if (iconMapperSubtitleText.hasOwnProperty(subText)) {
            const element = iconMapperSubtitleText[subText];
            changeFavicon(element);
            return;
        } 
    }

    // If site has TitleText - change to match
    for (const titleText of titleTexts) {
        tiText = titleText.textContent;
        if (iconMapperTitleText.hasOwnProperty(tiText)) {
            const element = iconMapperTitleText[tiText];
            changeFavicon(element);
            return;
        } 
    }

}
iconMapper()


// Otherwise keep current logo until page refresh or until a new page with known favicon is fetched
